### ISSUE TITLE
Compilation error - No class def BaseTypeFormat

### ISSUE THREAD

**Issue by baranidharan776** [Jyskebank/enunciate-openapi#27]
Am facing this problem when trying to run enunciate task 

Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/webcohesion/enunciate/api/datatype/BaseTypeFormat
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:693)
        at com.webcohesion.enunciate.gradle.EnunciateTask.configureAndInvokeEnunciate(EnunciateTask.java:261)
        at com.webcohesion.enunciate.gradle.EnunciateTask.run(EnunciateTask.java:220)
        ... 181 more
Caused by: java.lang.NoClassDefFoundError: com/webcohesion/enunciate/api/datatype/BaseTypeFormat
        at dk.jyskebank.tools.enunciate.modules.openapi.OpenApiTypeFormat.<clinit>(OpenApiTypeFormat.java:29)
        at dk.jyskebank.tools.enunciate.modules.openapi.DataTypeReferenceRenderer.renderType(DataTypeReferenceRenderer.java:112)
        at dk.jyskebank.tools.enunciate.modules.openapi.paths.ParameterRenderer.addType(ParameterRenderer.java:61)
        at dk.jyskebank.tools.enunciate.modules.openapi.paths.ParameterRenderer.exec(ParameterRenderer.java:48)
        at dk.jyskebank.tools.enunciate.modules.openapi.paths.ParameterRenderer.exec(ParameterRenderer.java:29)
        at dk.jyskebank.tools.enunciate.modules.freemarker.Typed1ArgTemplateMethod.exec(Typed1ArgTemplateMethod.java:41)
        at freemarker.core.MethodCall._eval(MethodCall.java:62)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
        at freemarker.core.Environment.visit(Environment.java:370)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:644)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:334)
        at freemarker.core.Environment.visit(Environment.java:376)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:644)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:370)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:644)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:334)
        at freemarker.core.Environment.visit(Environment.java:376)
        at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:3244)
        at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:78)
        at freemarker.core.Environment.visit(Environment.java:451)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:102)
        at freemarker.core.Environment.visit(Environment.java:334)
        at freemarker.core.Environment.visit(Environment.java:340)
        at freemarker.core.Environment.process(Environment.java:313)
        at freemarker.template.Template.process(Template.java:383)
        at dk.jyskebank.tools.enunciate.modules.openapi.OpenApiModule.processTemplate(OpenApiModule.java:296)
        at dk.jyskebank.tools.enunciate.modules.openapi.OpenApiModule$OpenApiInterfaceDescription.writeToFolder(OpenApiModule.java:220)
        at dk.jyskebank.tools.enunciate.modules.openapi.OpenApiModule.call(OpenApiModule.java:146)
        at com.webcohesion.enunciate.Enunciate.invokeModules(Enunciate.java:920)
        at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:127)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 186 more
Caused by: java.lang.ClassNotFoundException: com.webcohesion.enunciate.api.datatype.BaseTypeFormat
        ... 241 more

In build.gradle am configured as below

plugins
{
id "com.webcohesion.enunciate" version "2.13.1"
}

dependencies
{
 enunciate "dk.jyskebank.tooling.enunciate:enunciate-openapi:1.1.2"
}

**Comment by jskovjyskebankdk** [comment]
Are you using the latest gradle release?

**Comment by baranidharan776** [comment]
Gradle version is 5.5.1.

it's working fine when i changed enunciate version to 2.12.1

**Comment by jskovjyskebankdk** [comment]
Yes, I also saw it when trying to update to 2.13.1.
I have put a note in the README for now.

**Comment by mengjiann** [comment]
The same happened on Maven 3.5.4 with enunciate version 2.13.1.
